### PR TITLE
added nuxt create app example

### PR DESCRIPTION
**Pull request by sk-t3ch**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Extra, simpler example.

* **What is the current behavior?** (You can also link to an open issue here)
/

* **What is the new behavior (if this is a feature change)?**
/

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Currently a WIP, unsure if wanted

* **Other information**:

### CODE REVIEW

**Comment by ThornWalli** [comment]
Hi sk-t3ch,

Looked over the PR and probably understood what it's supposed to mean :)

Unfortunately, the solution in the PR is rather contra productive compared to the project structure.

There is now another repository with a clean Nuxt app with a simple example ([Nuxt Custom-Elements Example](https://github.com/GrabarzUndPartner/nuxt-custom-elements-example)) and the Usage section in the documentation extended with the example ([Nuxt Custom-Elements Docs - Usage](https://nuxt-custom-elements.grabarzundpartner.dev/usage)). 

For further suggestions for improvement, an issue would be useful.

**Comment by sk-t3ch** [comment]
Hi ThornWalli,

Great work, once again! Lovely example.

I am attempting to get this working with Vuetify. I am experiencing a lot of errors, do you think this is to be expected? Would you recommend attempting to recreate my component with something like tailWindCSS?

**Comment by ThornWalli** [comment]
What kind of problem do you get with Vuetify?

A simple integration works.

image

Have you tried using Tailwind?

**Comment by sk-t3ch** [comment]
I am able to get a simple example working. However, the more advanced components such as `v-tabs` and dark mode do not seem to be working. I have created a sandbox with my example - https://codesandbox.io/s/oij73

**Comment by ThornWalli** [comment]
I have added another example. In the example, a Vuetify component is used in nuxt and in a custom element.

https://grabarzundpartner.github.io/nuxt-custom-elements-example/vuetify/
https://grabarzundpartner.github.io/nuxt-custom-elements-example/vuetify/nuxt-custom-elements/example/

Use the Entry as a wrapper for Vuetify. 
Vuetify works independently and has no relation to the Nuxt module.

Now only the adoption of the CustomVariables is missing...

https://vuetifyjs.com/en/features/sass-variables/#variable-api

**Comment by sk-t3ch** [comment]
I am very grateful for your work. 
Your examples have enabled me to get my project working well.

...And I am now using the [`analyzer`](https://nuxt-custom-elements.grabarzundpartner.dev/options#analyzer) property to attempt to find out how to shrink the packaged component.

I'd be up for contributing in future, let me know if/how i can help.

**Pull request closed without merging**
